acreditation/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('careers.urls', namespace='careers')),
    url(r'^', include('evaluators.urls', namespace='evaluators')),
    url(r'^', include('userprofiles.urls', namespace='userprofiles')),
    url(r'^', include('namecareers.urls', namespace='namecareers')),
    url(r'^', include('resolutions.urls', namespace='resolutions')),
    url(r'^', include('nationalities.urls', namespace='nationalities')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

careers/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^acreditation/model/national/$', views.viewNational, name='national'),
    url(r'^acreditation/model/arcusur/$', views.viewArcusur, name='arcusur'),
    url(r'^acreditation/posgrado/$', views.viewPosgrado, name='postgrado'),
    url(r'^acreditation/postponed/$', views.viewPostponed, name='postponed'),
    url(r'^acreditation/no-reputable/$', views.viewNoReputable, name='noreputable'),
    url(r'^acreditation/history/$', views.viewHistory, name='history'),
    url(r'^acreditation/history/arcusur/$', views.viewHistoryArcusur, name='historyArcusur'),
    url(r'^acreditation/pdfnational/$', views.pdfNational, name='pdfNational'),
    url(r'^acreditation/pdfarcusur/$', views.pdfArcusur, name='pdfArcusur'),
    url(r'^acreditation/pdfpostponed/$', views.pdfPostponed, name='pdfPostponed'),
    url(r'^acreditation/pdfno-reputable/$', views.pdfNoReputable, name='pdfNoReputable'),
    url(r'^acreditation/pdfposgrado/$', views.pdfPosgrado, name='pdfPosgrado'),
    url(r'^acreditation/pdfhistory/$', views.pdfHistory, name='pdfHistory'),
    url(r'^acreditation/report/$', views.report, name='report'),
    url(r'^acreditation/cleanner/(?P<link>\w+)/$', views.cleanner, name='cleanner'),
    url(r'^acreditation/api/v1/$', views.careersJson, name='careersJson'),
    url(r'^acreditation/csvnational/$', views.exportCsvCareers, name='exportCsvCareers'),
    # url(r'^acreditation/v1/json/(?P<year>[0-9]+)/$', views.careersJson, name='careersJson'),
    # url(r'^acreditation/render-pdf/$', views.renderPdf, name='renderPdf'),
    # url(r'^acreditation/pdfnational/(?P<search>\w+[^/]+)/(?P<options>\w+)/$', views.pdfNational, name='pdfNational'),
    # url(r'^acreditation/pdfnational/(?P<search>\w+.+)/(?P<options>\w+)/$', views.pdfNational, name='pdfNational'),
    # url(r'^acreditation/pdfarcusur/(?P<search>\w+.+)/(?P<options>\w+)/$', views.pdfArcusur, name='pdfArcusur'),
]

careers/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from faculties.models import Faculty
from statuses.models import Status
from resolutions.models import Resolution
from namecareers.models import NameCareer

# Create your models here.

class Career(models.Model):
    fknamecareer = models.ForeignKey(NameCareer)
    fkstatus = models.ForeignKey(Status)
    fkresolution = models.OneToOneField(Resolution)
    fkfaculty = models.ForeignKey(Faculty)
    fkuser = models.ForeignKey(User)
    national = models.IntegerField(blank=True, null=True)
    arcusur = models.BooleanField(blank=False, default=False)
    posgrado = models.BooleanField(blank=False, default=False)

    def __str__(self):
        return self.fknamecareer.description

    class Meta:
        verbose_name = 'Carrer'
        verbose_name_plural = 'Careers'
        ordering = ('id',)

careers/forms.py
# coding=utf-8

# from django.forms import ModelForm
# from universities.models import University
from django import forms

# class FormUniversity(ModelForm):
#     class Meta:
#         model = University
#         exclude = ['id']

MY_CHOICES = (
    ('1', 'Carrera'),
    ('2', 'Universidad'),
    ('3', 'Facultad'),
    ('4', 'Sede'),
    ('5', 'Departamento'),
    ('6', 'Año'),
    ('7', 'Tipo Universidad'),
    )

class FormSearch(forms.Form):
    text = forms.CharField(label='Busqueda', error_messages={'required': 'Este campo es obligatorio'})
    options = forms.ChoiceField(choices=MY_CHOICES, widget=forms.RadioSelect, error_messages={'required': 'Este campo es obligatorio'})

# class FormUniversity(forms.Form):
#     university = forms.ModelMultipleChoiceField(queryset=University.objects.all(), error_messages={'required': 'Debe ingresar una universidad'})

careers/views.py
# coding=utf-8

from django.http import HttpResponse
#from django.shortcuts import render
from django.template import loader
from .models import Career
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from careers.forms import FormSearch
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import redirect
from django.core.urlresolvers import reverse
from django.db.models import Q
# Librerias para requeridas para generar pdf
from io import BytesIO
from reportlab.pdfgen import canvas
from reportlab.platypus import SimpleDocTemplate, Paragraph, TableStyle, Table, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_JUSTIFY, TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, inch, landscape, portrait, cm, A4
import urllib
import StringIO
import PIL.Image
from django.core import serializers
import json
import csv
from django.utils.encoding import smart_str

# Create your views here.

def viewNational(request):
    title = 'Carreras de Grado Modelo Nacional'
    template = loader.get_template('view_careers.html')
    label = 'national'
    request.session['s_text'] = ''
    request.session['s_options'] = ''
    if request.method == 'POST':
        form = FormSearch(request.POST)
        if form.is_valid():
            search = request.POST['text']
            options = request.POST['options']
            request.session['s_text'] = search
            request.session['s_options'] = options
            if options == '1':
                careers = Career.objects.filter(fknamecareer__description__icontains=search, fkstatus__description='Acreditada', arcusur=False, posgrado=False).order_by('fkresolution__start_date')
            elif options == '2':
                careers = Career.objects.filter(fkfaculty__fkuniversity__name__icontains=search, fkstatus__description='Acreditada', arcusur=False, posgrado=False).order_by('fkresolution__start_date')
            elif options == '3':
                careers = Career.objects.filter(fkfaculty__fkname__name__icontains=search, fkstatus__description='Acreditada', arcusur=False, posgrado=False).order_by('fkresolution__start_date')
            elif options == '4':
                careers = Career.objects.filter(fkfaculty__fkcampus__name__icontains=search, fkstatus__description='Acreditada', arcusur=False, posgrado=False).order_by('fkresolution__start_date')
            elif options == '5':
                careers = Career.objects.filter(fkfaculty__fkcampus__fkdepartment__name__icontains=search, fkstatus__description='Acreditada', arcusur=False, posgrado=False).order_by('fkresolution__start_date')
            elif options == '6':
                careers = Career.objects.filter(fkresolution__start_date__year=search, fkstatus__description='Acreditada', arcusur=False, posgrado=False).order_by('fkresolution__start_date')
            elif options == '7':
                careers = Career.objects.filter(fkfaculty__fkuniversity__fktypeuniversity__description__icontains=search, fkstatus__description='Acreditada', arcusur=False, posgrado=False).order_by('fkresolution__start_date')
            context = {
                'careers': careers,
                'title': title,
                'form': form,
                'label': label,
            }
            return HttpResponse(template.render(context, request))
    else:
        form = FormSearch()
    listCareer = Career.objects.filter(fkstatus__description='Acreditada', arcusur=False, posgrado=False).order_by('fkresolution__start_date')
    paginator = Paginator(listCareer, 10)
    try:
       page = int(request.GET.get('page', '1'))
    except ValueError:
       page = 1
    try:
       careers = paginator.page(page)
    except (EmptyPage, InvalidPage):
       careers = paginator.page(paginator.num_pages)
    context = {
        'careers': careers,
        'title': title,
        'form': form,
        'label': label,
    }
    return HttpResponse(template.render(context, request))

def viewHistory(request):    
    title = 'Historicos Carreras Acreditadas'
    template = loader.get_template('view_careers.html')
    label = 'history'
    request.session['s_text'] = ''
    request.session['s_options'] = ''
    if request.method == 'POST':
        form = FormSearch(request.POST)
        if form.is_valid():
            search = request.POST['text']
            options = request.POST['options']
            request.session['s_text'] = search
            request.session['s_options'] = options
            if options == '1':
                careers = Career.objects.filter(Q(fkstatus__description='Acreditada') | Q(fkstatus__description='Vencida'), fknamecareer__description__icontains=search, arcusur=False, posgrado=False).order_by('fkresolution__start_date')
            elif options == '2':
                careers = Career.objects.filter(Q(fkstatus__description='Acreditada') | Q(fkstatus__description='Vencida'), fkfaculty__fkuniversity__name__icontains=search, arcusur=False, posgrado=False).order_by('fkresolution__start_date')
            elif options == '3':
                careers = Career.objects.filter(Q(fkstatus__description='Acreditada') | Q(fkstatus__description='Vencida'), fkfaculty__fkname__name__icontains=search,  arcusur=False, posgrado=False).order_by('fkresolution__start_date')
            elif options == '4':
                careers = Career.objects.filter(Q(fkstatus__description='Acreditada') | Q(fkstatus__description='Vencida'), fkfaculty__fkcampus__name__icontains=search, arcusur=False, posgrado=False).order_by('fkresolution__start_date')
            elif options == '5':
                careers = Career.objects.filter(Q(fkstatus__description='Acreditada') | Q(fkstatus__description='Vencida'), fkfaculty__fkcampus__fkdepartment__name__icontains=search, arcusur=False, posgrado=False).order_by('fkresolution__start_date')
            elif options == '6':
                careers = Career.objects.filter(Q(fkstatus__description='Acreditada') | Q(fkstatus__description='Vencida'), fkresolution__start_date__year=search, arcusur=False, posgrado=False).order_by('fkresolution__start_date')
            elif options == '7':
                careers = Career.objects.filter(Q(fkstatus__description='Acreditada') | Q(fkstatus__description='Vencida'), fkfaculty__fkuniversity__fktypeuniversity__description__icontains=search, arcusur=False, posgrado=False).order_by('fkresolution__start_date')
            context = {
                'careers': careers,
                'title': title,
                'form': form,
                'label': label,
            }
            return HttpResponse(template.render(context, request))
    else:
        form = FormSearch()
    listCareer = Career.objects.filter(Q(fkstatus__description='Acreditada') | Q(fkstatus__description='Vencida'), arcusur=False, posgrado=False).order_by('fkresolution__start_date')
    paginator = Paginator(listCareer, 10)
    try:
       page = int(request.GET.get('page', '1'))
    except ValueError:
       page = 1
    try:
       careers = paginator.page(page)
    except (EmptyPage, InvalidPage):
       careers = paginator.page(paginator.num_pages)
    context = {
        'careers': careers,
        'title': title,
        'form': form,
        'label': label,
    }
    return HttpResponse(template.render(context, request))

def viewPostponed(request):
    title = 'Carreras de Grado/Programas de posgrado postergados Modelo Nacional'
    template = loader.get_template('view_postponed.html')
    label = 'postponed'
    request.session['s_text'] = ''
    request.session['s_options'] = ''
    if request.method == 'POST':
        form = FormSearch(request.POST)
        if form.is_valid():
            search = request.POST['text']
            options = request.POST['options']
            request.session['s_text'] = search
            request.session['s_options'] = options
            if options == '1':
                careers = Career.objects.filter(fknamecareer__description__icontains=search, fkstatus__description='Postergada', arcusur=False, posgrado=False).order_by('fkresolution__start_date')
            elif options == '2':
                careers = Career.objects.filter(fkfaculty__fkuniversity__name__icontains=search, fkstatus__description='Postergada', arcusur=False, posgrado=False).order_by('fkresolution__start_date')
            elif options == '3':
                careers = Career.objects.filter(fkfaculty__fkname__name__icontains=search, fkstatus__description='Postergada', arcusur=False, posgrado=False).order_by('fkresolution__start_date')
            elif options == '4':
                careers = Career.objects.filter(fkfaculty__fkcampus__name__icontains=search, fkstatus__description='Postergada', arcusur=False, posgrado=False).order_by('fkresolution__start_date')
            elif options == '5':
                careers = Career.objects.filter(fkfaculty__fkcampus__fkdepartment__name__icontains=search, fkstatus__description='Postergada', arcusur=False, posgrado=False).order_by('fkresolution__start_date')
            elif options == '6':
                careers = Career.objects.filter(fkresolution__start_date__year=search, fkstatus__description='Postergada', arcusur=False, posgrado=False).order_by('fkresolution__start_date')
            elif options == '7':
                careers = Career.objects.filter(fkfaculty__fkuniversity__fktypeuniversity__description__icontains=search, fkstatus__description='Postergada', arcusur=False, posgrado=False).order_by('fkresolution__start_date')
            context = {
                'careers': careers,
                'title': title,
                'form': form,
                'label': label,
            }
            return HttpResponse(template.render(context, request))
    else:
        form = FormSearch()

careers/templates/view_careers.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load careers_extras %}

{% block title %}
    {{ title }}
{% endblock %}

{% block header %}  
    {{ title|upper }}
{% endblock %}

{% block content %}

    <form method="POST">
        {% csrf_token %}
        <div class="form-group row">
            <label for="search" class="col-sm-2">Busqueda por: </label>
            <div class="col-sm-10">
                {% render_field form.text class="form-control" %}
                {{ form.text.errors }}
            </div>
            <div class="radio-inline">
                {% render_field form.options class="radio-inline" %}
                {{ form.options.errors }}
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Buscar</button>
        {% if label == 'national' %}
            <a href="{% url 'careers:pdfNational' %}" class="btn btn-primary">Generar Pdf</a>
            <a href="{% url 'careers:exportCsvCareers' %}" class="btn btn-primary">Generar CSV</a>
            <a href="{% url 'careers:cleanner' label %}" class="btn btn-primary">Limpiar</a>
        {% endif %}
        {% if label == 'arcusur' %}
            <a href="{% url 'careers:pdfArcusur' %}" class="btn btn-primary">Generar Pdf</a>
            <a href="{% url 'careers:cleanner' label %}" class="btn btn-primary">Limpiar</a>
        {% endif %}
        {% if label == 'history' %}
            <a href="{% url 'careers:pdfHistory' %}" class="btn btn-primary">Generar Pdf</a>
            <a href="{% url 'careers:cleanner' label %}" class="btn btn-primary">Limpiar</a>
        {% endif %}
    </form>

    <table class="table table-condensed table-striped">
        <thead>
            <tr>
                <th colspan="6" ></th>
                <th colspan="2">Periodo de Acreditación</th>
            </tr>
            <tr>
                <th>Nro.</th>
                <th>Carrera</th>
                <th>Institución</th>
                <th>Sede</th>
                <th>Facultad</th>
                {% if label == 'arcusur' %} <th>Acuerdo</th> {% else %} <th>Resolución</th> {% endif %}
                <th>Inicio</th>
                <th>Fin</th>
            </tr>
        </thead>
        <tbody>
            {% for c in careers %}
                <tr>
                    <td> {{ forloop.counter }} </td>
                    <td> {{ c.fknamecareer }} </td>
                    <td> {{ c.fkfaculty.fkuniversity }} </td>
                    <td> {{ c.fkfaculty.fkcampus }} </td>
                    <td> {{ c.fkfaculty.fkname }} </td>
                    <td> <a href="{{ c.fkresolution.document.url }}"> {{ c.fkresolution.number }} </a></td>
                    <td>{{ c.fkresolution.start_date|dateF1 }}</td>
                    <td>{{ c.fkresolution.end_date|dateF1 }}</td>
                </tr>
            {% endfor%}
        </tbody>
    </table>
    <ul class="pagination pagination-sm"> 
        {% if careers.has_previous %}
            <li><a href="?page={{ careers.previous_page_number }}">&laquo;</a></li>
            <!-- <li><a href="?page={{ careers.previous_page_number }}">&larr;</a></li> -->
        {% endif %}
        {% for pg in careers.paginator.page_range %}
            {% if careers.number == pg %}
                <li class="active"><a href="?page={{ pg }}">{{ pg }}</a></li>
            {% else %}
                <li><a href="?page={{ pg }}">{{pg}}</a></li>
            {% endif %}
        {% endfor %}
        {% if careers.has_next %}
            <li><a href="?page={{ careers.next_page_number }}">&raquo;</a></li>
            <!-- <li><a href="?page={{ careers.next_page_number }}">&rarr;</a></li> -->
        {% endif %}
    </ul>
{% endblock %}

careers/templates/view_posgrado.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load careers_extras %}

{% block title %}
    {{ title }}
{% endblock %}

{% block header %}  
    {{ title|upper }}
{% endblock %} 

{% block content %}

    <form method="POST">
        {% csrf_token %}
        <div class="form-group row">
            <label for="search" class="col-sm-2">Busqueda por:</label>
            <div class="col-sm-10">
                {% render_field form.text class="form-control" %}
                {{ form.text.errors }}
            </div>
            <div class="radio-inline">
                {% render_field form.options class="radio-inline" %}
                {{ form.options.errors }}
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Buscar</button>
        <a href="{% url 'careers:pdfPosgrado' %}" class="btn btn-primary">Generar Pdf</a>
        <a href="{% url 'careers:cleanner' label %}" class="btn btn-primary">Limpiar</a>
    </form>

    <table class="table table-condensed table-striped">
        <thead>
            <tr>
                <th>Nro.</th>
                <th>Programa de Posgrado</th>
                <th>Institución</th>
                <th>Sede</th>
                <th>Resolución</th>
                <th>Fecha</th>
                <th>Período de Acreditación</th>
            </tr>
        </thead>
        <tbody>
            {% for c in careers %}
                <tr>
                    <td> {{ forloop.counter }} </td>
                    <td> {{ c.fknamecareer }} </td>
                    <td> {{ c.fkfaculty.fkuniversity }} </td>
                    <td> {{ c.fkfaculty.fkcampus }} </td>
                    <td> <a href="{{ c.fkresolution.document.url }}"> {{ c.fkresolution.number }} </a> </td>
                    <td> {{ c.fkresolution.start_date|dateF1 }} </td>
                    <td> {{ c.fkresolution.end_date|dateF1 }} </td>
                </tr>
            {% endfor%}
        </tbody>
    </table>
    <ul class="pagination pagination-sm"> 
        {% if careers.has_previous %}
            <li><a href="?page={{ careers.previous_page_number }}">&laquo;</a></li>
            <!-- <li><a href="?page={{ careers.previous_page_number }}">&larr;</a></li> -->
        {% endif %}
        {% for pg in careers.paginator.page_range %}
            {% if careers.number == pg %}
                <li class="active"><a href="?page={{ pg }}">{{ pg }}</a></li>
            {% else %}
                <li><a href="?page={{ pg }}">{{pg}}</a></li>
            {% endif %}
        {% endfor %}
        {% if careers.has_next %}
            <li><a href="?page={{ careers.next_page_number }}">&raquo;</a></li>
            <!-- <li><a href="?page={{ careers.next_page_number }}">&rarr;</a></li> -->
        {% endif %}
    </ul>
{% endblock %}

careers/templates/view_postponed.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load careers_extras %}

{% block title %}
    {{ title }}
{% endblock %}

{% block header %}  
    {{ title|upper }}
{% endblock %} 

{% block content %}

    <form method="POST">
        {% csrf_token %}
        <div class="form-group row">
            <label for="search" class="col-sm-2">Busqueda por:</label>
            <div class="col-sm-10">
                {% render_field form.text class="form-control" %}
                {{ form.text.errors }}
            </div>
            <div class="radio-inline">
                {% render_field form.options class="radio-inline" %}
                {{ form.options.errors }}
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Buscar</button>
        {% if label == 'postponed' %}
            <a href="{% url 'careers:pdfPostponed' %}" class="btn btn-primary">Generar Pdf</a>
            <a href="{% url 'careers:cleanner' label %}" class="btn btn-primary">Limpiar</a>
        {% endif %}
        {% if label == 'noreputable' %}
            <a href="{% url 'careers:pdfNoReputable' %}" class="btn btn-primary">Generar Pdf</a>
            <a href="{% url 'careers:cleanner' label %}" class="btn btn-primary">Limpiar</a>
        {% endif %}
    </form>

    <table class="table table-condensed table-striped">
        <thead>
            <tr>
                <th>Nro.</th>
                <th>Universidades/Institutos Superiores</th>
                <th>Carrera/Programa</th>
                <th>Sede</th>
                <th>Resolución</th>
            </tr>
        </thead>
        <tbody>
            {% for c in careers %}
                <tr>
                    <td> {{ forloop.counter }} </td>
                    <td> {{ c.fkfaculty.fkuniversity }} </td>
                    <td> {{ c.fknamecareer }} </td>
                    <td> {{ c.fkfaculty.fkcampus }} </td>
                    <td> <a href="{{ c.fkresolution.document.url }}"> {{ c.fkresolution.number }} / {{ c.fkresolution.start_date|dateF2 }} </a></td>
                </tr>
            {% endfor%}
        </tbody>
    </table>
    <ul class="pagination pagination-sm"> 
        {% if careers.has_previous %}
            <li><a href="?page={{ careers.previous_page_number }}">&laquo;</a></li>
            <!-- <li><a href="?page={{ careers.previous_page_number }}">&larr;</a></li> -->
        {% endif %}
        {% for pg in careers.paginator.page_range %}
            {% if careers.number == pg %}
                <li class="active"><a href="?page={{ pg }}">{{ pg }}</a></li>
            {% else %}
                <li><a href="?page={{ pg }}">{{pg}}</a></li>
            {% endif %}
        {% endfor %}
        {% if careers.has_next %}
            <li><a href="?page={{ careers.next_page_number }}">&raquo;</a></li>
            <!-- <li><a href="?page={{ careers.next_page_number }}">&rarr;</a></li> -->
        {% endif %}
    </ul>
{% endblock %}

careers/templates/view_test.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load careers_extras %}

{% block title %}
    {{ title }}
{% endblock %}

{% block header %}  
    {{ title|upper }}
{% endblock %} 

{% block content %}

    <p>{{ search }}</p>
    <p>{{ options }}</p>


{% endblock %}