acreditation/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('careers.urls', namespace='careers')),
    url(r'^', include('evaluators.urls', namespace='evaluators')),
    url(r'^', include('userprofiles.urls', namespace='userprofiles')),
    url(r'^', include('namecareers.urls', namespace='namecareers')),
    url(r'^', include('resolutions.urls', namespace='resolutions')),
    url(r'^', include('nationalities.urls', namespace='nationalities')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

careers/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^acreditation/model/national/$', views.viewNational, name='national'),
    url(r'^acreditation/model/arcusur/$', views.viewArcusur, name='arcusur'),
    url(r'^acreditation/posgrado/$', views.viewPosgrado, name='postgrado'),
    url(r'^acreditation/postponed/$', views.viewPostponed, name='postponed'),
    url(r'^acreditation/no-reputable/$', views.viewNoReputable, name='noreputable'),
    url(r'^acreditation/history/$', views.viewHistory, name='history'),
    url(r'^acreditation/history/arcusur/$', views.viewHistoryArcusur, name='historyArcusur'),
    url(r'^acreditation/pdfnational/$', views.pdfNational, name='pdfNational'),
    url(r'^acreditation/pdfarcusur/$', views.pdfArcusur, name='pdfArcusur'),
    url(r'^acreditation/pdfpostponed/$', views.pdfPostponed, name='pdfPostponed'),
    url(r'^acreditation/pdfno-reputable/$', views.pdfNoReputable, name='pdfNoReputable'),
    url(r'^acreditation/pdfposgrado/$', views.pdfPosgrado, name='pdfPosgrado'),
    url(r'^acreditation/pdfhistory/$', views.pdfHistory, name='pdfHistory'),
    url(r'^acreditation/report/$', views.report, name='report'),
    url(r'^acreditation/cleanner/(?P<link>\w+)/$', views.cleanner, name='cleanner'),
    url(r'^acreditation/api/v1/$', views.careersJson, name='careersJson'),
    url(r'^acreditation/csvnational/$', views.exportCsvCareers, name='exportCsvCareers'),
    # url(r'^acreditation/v1/json/(?P<year>[0-9]+)/$', views.careersJson, name='careersJson'),
    # url(r'^acreditation/render-pdf/$', views.renderPdf, name='renderPdf'),
    # url(r'^acreditation/pdfnational/(?P<search>\w+[^/]+)/(?P<options>\w+)/$', views.pdfNational, name='pdfNational'),
    # url(r'^acreditation/pdfnational/(?P<search>\w+.+)/(?P<options>\w+)/$', views.pdfNational, name='pdfNational'),
    # url(r'^acreditation/pdfarcusur/(?P<search>\w+.+)/(?P<options>\w+)/$', views.pdfArcusur, name='pdfArcusur'),
]

evaluators/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^dashboard/evaluator/institutional/$', views.viewEvaluatorInstitutional, name='institutional'),
    url(r'^dashboard/evaluator/degree/$', views.viewEvaluatorDegree, name='degree'),
    url(r'^dashboard/evaluator/arcusur/$', views.viewEvaluatorArcusur, name='arcusur'),
    url(r'^dashboard/evaluator/list/$', views.viewEvaluator, name='evaluator'),
    url(r'^dashboard/evaluator/add/new/$', views.newEvaluator, name='new'),
    url(r'^dashboard/evaluator/edit/(?P<pk>[0-9]+)/$', views.editEvaluator, name='edit'),
    # url(r'^dashboard/evaluator/add/type/$', views.newTypeEvaluator, name='newtype'),
    url(r'^dashboard/evaluator/edit/type/(?P<pk>[0-9]+)/$', views.editTypeEvaluator, name='editType'),
    url(r'^dashboard/evaluator/list/institutional/$', views.searchInstitutional, name='searchInstitutional'),
    url(r'^dashboard/evaluator/list/degree/$', views.searchDegree, name='searchDegree'),
    url(r'^dashboard/evaluator/list/arcusur/$', views.searchArcusur, name='searchArcusur'),
    # url(r'^dashboard/evaluator/add/declaration/$', views.newDeclaration, name='newDeclaration'),
    url(r'^dashboard/evaluator/add/declaration/(?P<user>[0-9]+)$', views.newDeclaration, name='newDeclaration'),
    url(r'^dashboard/evaluator/edit/declaration/(?P<pk>[0-9]+)/$', views.editDeclaration, name='editDeclaration'),
    url(r'^dashboard/evaluator/list/declaration/$', views.viewDeclaration, name='viewDeclaration'),
    url(r'^dashboard/evaluator/declaration/$', views.searchDeclaration, name='searchDeclaration'),
    url(r'^dashboard/evaluator/cleanner/(?P<link>\w+)/$', views.cleanner, name='cleanner'),
    url(r'^dashboard/evaluator/list/view/$', views.EvaluatorList.as_view(), name='list'),
    url(r'^dashboard/evaluator/add/type/(?P<label>[0-9]+)/(?P<user>[0-9]+)$', views.newEvaluatorInstitutional, name='addType'),
    # url(r'^dashboard/evaluator/list/institutional/$', views.ListInstitutional.as_view(), name='listInstitutional'),
    url(r'^acreditation/api/v2/$', views.apiJson2, name='apiJson2'),
    url(r'^acreditation/api/v3/$', views.getTemplate, name='getTemplate'),
    url(r'^acreditation/api/v4/$', views.apiJson3, name='apiJson4'),
    # url(r'^acreditation/api/form/$', views.getTemplate, name='getTemplate'),
    url(r'^acreditation/api/v5/$', views.apiJson5, name='apiJson5'),
    url(r'^dashboard/evaluator/list/agronomia/$', views.ListAgronomia.as_view(), name='listAgronomia'),
    url(r'^dashboard/evaluator/(?P<pk>[0-9]+)/$', views.EvaluatorDetail.as_view(), name='EvaluatorDetail'),
    url(r'^acreditation/pdfevaluator/$', views.pdfEvaluator, name='pdfEvaluator'),
]

evaluators/forms.py
from django import forms
from .models import Evaluator, TypesEvaluator, EvaluatorUniversity
from statuses.models import Status
from django.db.models import Q

class EvaluatorForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(EvaluatorForm, self).__init__(*args, **kwargs)
        self.fields['fkstatus'].queryset = Status.objects.filter(Q(description='Activo') | Q(description='Inactivo'))

    class Meta:
        model = Evaluator
        fields = ['firstname', 'lastname', 'ci', 'email',  'curriculum', 'fkstatus', 'fknationality' ]
        # exclude = ['typesevaluators', ]

class TypeEvaluatorForm(forms.ModelForm):
    class Meta:
        model = TypesEvaluator
        fields = ('__all__')

class EvaluatorUniversityForm(forms.ModelForm):
    class Meta:
        model = EvaluatorUniversity
        fields = ('__all__')

MY_INSTITUTIONAL = (
    ('1', 'Nombre'),
    ('2', 'Apellido'),
    )

class FormSearchIns(forms.Form):
    text = forms.CharField(label='Busqueda', error_messages={'required': 'Este campo es obligatorio'})
    options = forms.ChoiceField(choices=MY_INSTITUTIONAL, widget=forms.RadioSelect, error_messages={'required': 'Este campo es obligatorio'})


MY_DEGREE = (
    ('1', 'Nombre'),
    ('2', 'Apellido'),
    ('3', 'Carrera'),
    )

class FormSearchDegree(forms.Form):
    text = forms.CharField(label='Busqueda', error_messages={'required': 'Este campo es obligatorio'})
    options = forms.ChoiceField(choices=MY_DEGREE, widget=forms.RadioSelect, error_messages={'required': 'Este campo es obligatorio'})

# class MyModelForm(forms.ModelForm):
#     def __init__(self, request, *args, **kwargs):
#         # request is a required parameter for this form.
#         super(MyModelForm, self).__init__(*args, **kwargs)
#         self.fields['website'].queryset = Website.objects.filter(organization__primary_account=request.user)

evaluators/views.py
# coding=utf-8

from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from .models import TypesEvaluator, Evaluator, EvaluatorUniversity
from statuses.models import Status
from typeevaluators.models import TypeEvaluator
from namecareers.models import NameCareer
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.decorators import login_required
from .forms import EvaluatorForm, TypeEvaluatorForm, EvaluatorUniversityForm, FormSearchIns, FormSearchDegree
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.db import IntegrityError
from django.db.models import Q
import json
from io import BytesIO
from reportlab.pdfgen import canvas
from reportlab.platypus import SimpleDocTemplate, Paragraph, TableStyle, Table, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_JUSTIFY, TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, inch, landscape, portrait, cm, A4
import urllib
import StringIO
import PIL.Image

@login_required(login_url='/login/')
def viewEvaluatorInstitutional(request):
    title = 'Pares Evaluadores Institucionales'
    template = loader.get_template('view_evaluator_institutional.html')
    request.session['s_text'] = ''
    request.session['s_options'] = ''
    if request.method == 'POST':
        form = FormSearchIns(request.POST)
        if form.is_valid():
            search = request.POST['text']
            options = request.POST['options']
            request.session['s_text'] = search
            request.session['s_options'] = options
            if options == '1':
                listEvaluator = TypesEvaluator.objects.filter(fktypeevaluator__description__icontains='Institucional', fkevaluator__firstname__icontains=search, fkevaluator__fkstatus__description='Activo')
            elif options == '2':
                listEvaluator = TypesEvaluator.objects.filter(fktypeevaluator__description__icontains='Institucional', fkevaluator__lastname__icontains=search, fkevaluator__fkstatus__description='Activo')
            context = {
                'title': title,
                'listEvaluator': listEvaluator,
                'form': form,
            }
            return HttpResponse(template.render(context, request))
    else:
        form = FormSearchIns()
    listPaginator = TypesEvaluator.objects.filter(fktypeevaluator__description__icontains='Institucional', fkevaluator__fkstatus__description='Activo')
    paginator = Paginator(listPaginator, 10)
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1
    try:
        listEvaluator = paginator.page(page)
    except (EmptyPage, InvalidPage):
        listEvaluator = paginator.page(paginator.num_pages)
    context = {
        'title': title,
        'listEvaluator': listEvaluator,
        'form': form,
    }
    return HttpResponse(template.render(context, request))

@login_required(login_url='/login/')
def viewEvaluatorDegree(request):
    title = 'Pares Evaluadores de Carreras de Grado'
    template = loader.get_template('view_evaluator_degree.html')
    request.session['s_text'] = ''
    request.session['s_options'] = ''
    if request.method == 'POST':
        form = FormSearchDegree(request.POST)
        if form.is_valid():
            search = request.POST['text']
            options = request.POST['options']
            request.session['s_text'] = search
            request.session['s_options'] = options
            if options == '1':
                listEvaluator = TypesEvaluator.objects.filter(fktypeevaluator__description__icontains='Carreras de Grado', fkevaluator__fkstatus__description='Activo', fkevaluator__firstname__icontains=search)
            elif options == '2':
                listEvaluator = TypesEvaluator.objects.filter(fktypeevaluator__description__icontains='Carreras de Grado', fkevaluator__fkstatus__description='Activo', fkevaluator__lastname__icontains=search)
            elif options == '3':
                listEvaluator = TypesEvaluator.objects.filter(fktypeevaluator__description__icontains='Carreras de Grado', fkevaluator__fkstatus__description='Activo', fknamecareer__description__icontains=search)
            context = {
                'title': title,
                'listEvaluator': listEvaluator,
                'form': form,
            }
            return HttpResponse(template.render(context, request))
    else:
        form = FormSearchDegree()
    listPaginator = TypesEvaluator.objects.filter(fktypeevaluator__description__icontains='Carreras de Grado', fkevaluator__fkstatus__description='Activo')
    paginator = Paginator(listPaginator, 10)
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1
    try:
        listEvaluator = paginator.page(page)
    except (EmptyPage, InvalidPage):
        listEvaluator = paginator.page(paginator.num_pages)
    context = {
        'title': title,
        'listEvaluator': listEvaluator,
        'form': form,
    }
    return HttpResponse(template.render(context, request))

@login_required(login_url='/login/')
def viewEvaluatorArcusur(request):
    title = 'Pares Evaluadores de Carreras de Grado Modelo Arcusur'
    template = loader.get_template('view_evaluator_degree.html')
    request.session['s_text'] = ''
    request.session['s_options'] = ''
    if request.method == 'POST':
        form = FormSearchDegree(request.POST)
        if form.is_valid():
            search = request.POST['text']
            options = request.POST['options']
            request.session['s_text'] = search
            request.session['s_options'] = options
            if options == '1':
                listEvaluator = TypesEvaluator.objects.filter(fktypeevaluator__description__icontains='Arcusur', fkevaluator__fkstatus__description='Activo', fkevaluator__firstname__icontains=search)
            elif options == '2':
                listEvaluator = TypesEvaluator.objects.filter(fktypeevaluator__description__icontains='Arcusur', fkevaluator__fkstatus__description='Activo', fkevaluator__lastname__icontains=search)
            elif options == '3':
                listEvaluator = TypesEvaluator.objects.filter(fktypeevaluator__description__icontains='Arcusur', fkevaluator__fkstatus__description='Activo', fknamecareer__description__icontains=search)
            context = {
                'title': title,
                'listEvaluator': listEvaluator,
                'form': form,
            }
            return HttpResponse(template.render(context, request))
    else:
        form = FormSearchDegree()
    listPaginator = TypesEvaluator.objects.filter(fktypeevaluator__description__icontains='Arcusur', fkevaluator__fkstatus__description='Activo')
    paginator = Paginator(listPaginator, 10)
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1
    try:
        listEvaluator = paginator.page(page)
    except (EmptyPage, InvalidPage):
        listEvaluator = paginator.page(paginator.num_pages)
    context = {
        'title': title,
        'listEvaluator': listEvaluator,
        'form': form,
    }
    return HttpResponse(template.render(context, request))

@login_required(login_url='/login/')
def viewEvaluator(request):
    title = 'Pares Evaluadores'
    template = loader.get_template('list_evaluator.html')
    request.session['s_text'] = ''
    request.session['s_options'] = ''
    if request.method == 'POST':
        form = FormSearchIns(request.POST)
        if form.is_valid():
            search = request.POST['text']
            options = request.POST['options']
            request.session['s_text'] = search
            request.session['s_options'] = options
            if options == '1':
                listEvaluator = Evaluator.objects.filter(firstname__icontains=search)
            elif options == '2':
                listEvaluator = Evaluator.objects.filter(lastname__icontains=search)
            context = {
                'title': title,
                'listEvaluator': listEvaluator,
                'form': form,
            }
            return HttpResponse(template.render(context, request))
    else:
        form = FormSearchIns()
    listPaginator = Evaluator.objects.all()
    paginator = Paginator(listPaginator, 10)
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1
    try:
        listEvaluator = paginator.page(page)
    except (EmptyPage, InvalidPage):
        listEvaluator = paginator.page(paginator.num_pages)
    context = {
        'title': title,
        'listEvaluator': listEvaluator,
        'form': form,
    }
    return HttpResponse(template.render(context, request))

@login_required(login_url='/login/')
def newEvaluator(request):
    title = 'Agregar nuevo par'
    template = loader.get_template('new_evaluator.html')
    if request.method == 'POST':
        form = EvaluatorForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            url = 'evaluators:evaluator'
            return HttpResponseRedirect(reverse(url))
    else:
        form = EvaluatorForm()
    context = {
        'title': title,
        'form': form,
    }
    return HttpResponse(template.render(context, request))

@login_required(login_url='/login/')
def editEvaluator(request, pk):
    title = 'Actualizar par'
    template = loader.get_template('new_evaluator.html')
    ins = get_object_or_404(Evaluator,pk=pk)
    if request.method == 'POST':
        form = EvaluatorForm(request.POST, request.FILES, instance=ins)
        if form.is_valid():
            form.save()
            url = 'evaluators:evaluator'

evaluators/templates/list_evaluator.html
{% extends 'layout.html' %}
{% load widget_tweaks %}

{% block title %}
    {{ title }}
{% endblock %}

{% block header %}  
    {{ title|upper }}
{% endblock %} 

{% block content %}

    <form method="POST">
        {% csrf_token %}
        <div class="form-group row">
            <label for="search" class="col-sm-2">Busqueda por:</label>
            <div class="col-sm-6">
                {% render_field form.text class="form-control" %}
                <strong class="text-danger"> {{ form.text.errors }} </strong>
            </div>
            <div class="radio-inline">
                {% render_field form.options class="radio-inline" %}
                <strong class="text-danger"> {{ form.options.errors }} </strong>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Buscar</button>
        <a href="{% url 'evaluators:evaluator' %}" class="btn btn-primary">Limpiar</a>
    </form>

    {% for item in user.user_profile.all %}
    {% if item.number == 777 %}

    <table class="table table-condensed table-striped">
        <thead>
            <tr>
                <th colspan="4"><a href="{% url 'evaluators:new' %}" class="btn btn-success btn-sm"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a> </th>
            </tr>
            <tr>
                <th>Edit</th>
                <th>Institucional</th>
                <th>Grado</th>
                <th>Arcusur</th>
                <th>Declaración</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Cedula</th>
                <th>E-mail</th>
                <th>Curriculum</th>
            </tr>
        </thead>
        <tbody>
            {% for ev in listEvaluator %}
                <tr>
                    <td> <a href="{% url 'evaluators:edit' ev.id %}" class="btn btn-success btn-sm"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></a></td>
                    <td> <a href="{% url 'evaluators:addType' 2 ev.id %}" class="btn btn-success btn-sm"><span class="glyphicon glyphicon-italic" aria-hidden="true"></span></a></td>
                    <td> <a href="{% url 'evaluators:addType' 1 ev.id %}" class="btn btn-success btn-sm"><span class="glyphicon glyphicon-education" aria-hidden="true"></span></a></td>
                    <td> <a href="{% url 'evaluators:addType' 3 ev.id %}" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-education" aria-hidden="true"></span></a></td>
                    <td> <a href="{% url 'evaluators:newDeclaration' ev.id %}" class="btn btn-success btn-sm"><span class="glyphicon glyphicon-book" aria-hidden="true"></span></a></td>
                    <td> {{ ev.firstname }} </td>
                    <td> {{ ev.lastname }} </td>
                    <td> {{ ev.ci }} </td>
                    <td> {{ ev.email }} </td>
                    {% if ev.curriculum.url != "" %}
                        <td> <a href="{{ ev.curriculum.url }}" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></a></td>
                    {% else %}
                        <td><div class="btn btn-info btn-sm"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></div></td>
                    {% endif %}
                </tr>
            {% endfor%}
        </tbody>
    </table>
    {% else %}
    <table class="table table-condensed table-striped">
        <thead>
            <tr>
                <th>Declaración</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Cedula</th>
                <th>E-mail</th>
                <th>Curriculum</th>
            </tr>
        </thead>
        <tbody>
            {% for ev in listEvaluator %}
                <tr>
                    <td> <a href="{% url 'evaluators:newDeclaration' ev.id %}" class="btn btn-success btn-sm"><span class="glyphicon glyphicon-book" aria-hidden="true"></span></a></td>
                    <td> {{ ev.firstname }} </td>
                    <td> {{ ev.lastname }} </td>
                    <td> {{ ev.ci }} </td>
                    <td> {{ ev.email }} </td>
                    {% if ev.curriculum.url != "" %}
                        <td> <a href="{{ ev.curriculum.url }}" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></a></td>
                    {% else %}
                        <td><div class="btn btn-info btn-sm"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></div></td>
                    {% endif %}
                </tr>
            {% endfor%}
        </tbody>
    </table>
    {% endif %}
    {% endfor %}
    
    <ul class="pagination pagination-sm"> 
        {% if listEvaluator.has_previous %}
            <li><a href="?page={{ listEvaluator.previous_page_number }}" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></a></li>
        {% endif %}
        {% for pg in listEvaluator.paginator.page_range %}
            {% if listEvaluator.number == pg %}
                <li class="active"><a href="?page={{ pg }}">{{ pg }}</a></li>
            {% else %}
                <li><a href="?page={{ pg }}">{{pg}}</a></li>
            {% endif %}
        {% endfor %}
        {% if listEvaluator.has_next %}
            <li><a href="?page={{ listEvaluator.next_page_number }}" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></a></li>
        {% endif %}
    </ul>
{% endblock %}

evaluators/templates/searchevaluator_list.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load careers_extras %}

{% block title %}
    {{ title }}
{% endblock %}

{% block header %}  
    {{ title|upper }}
{% endblock %} 

{% block content %}

    <form method="POST">
        {% csrf_token %}
        <div class="form-group row">
            <label for="search" class="col-sm-2">Busqueda por:</label>
            <div class="col-sm-6">
                {% render_field form.text class="form-control" %}
                <strong class="text-danger"> {{ form.text.errors }} </strong>
            </div>
            <div class="radio-inline">
                {% render_field form.options class="radio-inline" %}
                <strong class="text-danger"> {{ form.options.errors }} </strong>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Buscar</button>
        {% if label == 'institutional' %}
            <a href="{% url 'evaluators:pdfEvaluator' %}" class="btn btn-primary">Generar pdf</a>
            <a href="{% url 'evaluators:cleanner' label %}" class="btn btn-primary">Limpiar</a>
        {% endif %}
        {% if label == 'degree' %}
            <a href="{% url 'evaluators:pdfEvaluator' %}" class="btn btn-primary">Generar pdf</a>
            <a href="{% url 'evaluators:cleanner' label %}" class="btn btn-primary">Limpiar</a>
        {% endif %}
        {% if label == 'arcusur' %}
            <a href="{% url 'evaluators:pdfEvaluator' %}" class="btn btn-primary">Generar pdf</a>
            <a href="{% url 'evaluators:cleanner' label %}" class="btn btn-primary">Limpiar</a>
        {% endif %}
    </form>

    <table class="table table-condensed table-striped">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Apellido</th>
                {% if label == 'degree' or label == 'arcusur' %}<th> Carrera </th>{% endif %}
                <th>Curriculum</th>
                <th>Resolución</th>
            </tr>
        </thead>
        <tbody>
            {% for te in typesEvaluatorList %}
                <tr>
                    <td> {{ te.fkevaluator.firstname }} </td>
                    <td> {{ te.fkevaluator.lastname }} </td>
                    {% if label == 'degree' or label == 'arcusur' %} <td> {{ te.fknamecareer.description }} </td> {% endif %}
                    {% if te.fkevaluator.curriculum.url != "" %}
                        <td> <a href="{{ te.fkevaluator.curriculum.url }}" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></a></td>
                    {% else %}
                        <td><div class="btn btn-info btn-sm"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></div></td>
                    {% endif %}
                    <td> <a href="{{ te.fkresolution.document.url }}" class="btn btn-info btn-sm"> <span class="glyphicon glyphicon-file" aria-hidden="true"> {{ te.fkresolution.number }} </a></td>
                </tr>
            {% endfor%}
        </tbody>
    </table>
{% endblock %}

evaluators/templates/view_declaration.html
{% extends 'layout.html' %}
{% load widget_tweaks %}

{% block title %}
    {{ title }}
{% endblock %}

{% block header %}  
    {{ title|upper }}
{% endblock %} 

{% block content %}

    {% if error %}
        <div class="form-group row">
            <div class="col-sm-10">
                <strong class="text-danger text-center"> {{ error|upper }} </strong>
            </div>
        </div>
    {% endif %}
    
    <form method="POST">
        {% csrf_token %}
        <div class="form-group row">
            <label for="search" class="col-sm-2">Busqueda por:</label>
            <div class="col-sm-6">
                {% render_field form.text class="form-control" %}
                <strong class="text-danger"> {{ form.text.errors }} </strong>
            </div>
            <div class="radio-inline">
                {% render_field form.options class="radio-inline" %}
                <strong class="text-danger"> {{ form.options.errors }} </strong>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Buscar</button>
        <a href="{% url 'evaluators:viewDeclaration' %}" class="btn btn-primary">Limpiar</a>
    </form>

    <table class="table table-condensed table-striped">
        <thead>
            <tr>
                <th>Edit</th>
                <th>Nombre</th>
                <th>Universidad</th>
                <th>Motivo</th>
            </tr>
        </thead>
        <tbody>
            {% for de in listDeclaration %}
                <tr>
                    <td> <a href="{% url 'evaluators:editDeclaration' de.id %}" class="btn btn-success btn-sm"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></a></td>
                    <td> {{ de.fkevaluator.fullname }} </td>
                    <td> {{ de.fkuniversity.name }} </td>
                    <td> {{ de.reason }} </td>
                </tr>
            {% endfor%}
        </tbody>
    </table>
    <ul class="pagination pagination-sm"> 
        {% if listEvaluator.has_previous %}
            <li><a href="?page={{ listEvaluator.previous_page_number }}" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></a></li>
        {% endif %}
        {% for pg in listEvaluator.paginator.page_range %}
            {% if listEvaluator.number == pg %}
                <li class="active"><a href="?page={{ pg }}">{{ pg }}</a></li>
            {% else %}
                <li><a href="?page={{ pg }}">{{pg}}</a></li>
            {% endif %}
        {% endfor %}
        {% if listEvaluator.has_next %}
            <li><a href="?page={{ listEvaluator.next_page_number }}" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></a></li>
        {% endif %}
    </ul>
{% endblock %}