acreditation/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('careers.urls', namespace='careers')),
    url(r'^', include('evaluators.urls', namespace='evaluators')),
    url(r'^', include('userprofiles.urls', namespace='userprofiles')),
    url(r'^', include('namecareers.urls', namespace='namecareers')),
    url(r'^', include('resolutions.urls', namespace='resolutions')),
    url(r'^', include('nationalities.urls', namespace='nationalities')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

careers/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^acreditation/model/national/$', views.viewNational, name='national'),
    url(r'^acreditation/model/arcusur/$', views.viewArcusur, name='arcusur'),
    url(r'^acreditation/posgrado/$', views.viewPosgrado, name='postgrado'),
    url(r'^acreditation/postponed/$', views.viewPostponed, name='postponed'),
    url(r'^acreditation/no-reputable/$', views.viewNoReputable, name='noreputable'),
    url(r'^acreditation/history/$', views.viewHistory, name='history'),
    url(r'^acreditation/history/arcusur/$', views.viewHistoryArcusur, name='historyArcusur'),
    url(r'^acreditation/pdfnational/$', views.pdfNational, name='pdfNational'),
    url(r'^acreditation/pdfarcusur/$', views.pdfArcusur, name='pdfArcusur'),
    url(r'^acreditation/pdfpostponed/$', views.pdfPostponed, name='pdfPostponed'),
    url(r'^acreditation/pdfno-reputable/$', views.pdfNoReputable, name='pdfNoReputable'),
    url(r'^acreditation/pdfposgrado/$', views.pdfPosgrado, name='pdfPosgrado'),
    url(r'^acreditation/pdfhistory/$', views.pdfHistory, name='pdfHistory'),
    url(r'^acreditation/report/$', views.report, name='report'),
    url(r'^acreditation/cleanner/(?P<link>\w+)/$', views.cleanner, name='cleanner'),
    url(r'^acreditation/api/v1/$', views.careersJson, name='careersJson'),
    url(r'^acreditation/csvnational/$', views.exportCsvCareers, name='exportCsvCareers'),
    # url(r'^acreditation/v1/json/(?P<year>[0-9]+)/$', views.careersJson, name='careersJson'),
    # url(r'^acreditation/render-pdf/$', views.renderPdf, name='renderPdf'),
    # url(r'^acreditation/pdfnational/(?P<search>\w+[^/]+)/(?P<options>\w+)/$', views.pdfNational, name='pdfNational'),
    # url(r'^acreditation/pdfnational/(?P<search>\w+.+)/(?P<options>\w+)/$', views.pdfNational, name='pdfNational'),
    # url(r'^acreditation/pdfarcusur/(?P<search>\w+.+)/(?P<options>\w+)/$', views.pdfArcusur, name='pdfArcusur'),
]

evaluators/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^dashboard/evaluator/institutional/$', views.viewEvaluatorInstitutional, name='institutional'),
    url(r'^dashboard/evaluator/degree/$', views.viewEvaluatorDegree, name='degree'),
    url(r'^dashboard/evaluator/arcusur/$', views.viewEvaluatorArcusur, name='arcusur'),
    url(r'^dashboard/evaluator/list/$', views.viewEvaluator, name='evaluator'),
    url(r'^dashboard/evaluator/add/new/$', views.newEvaluator, name='new'),
    url(r'^dashboard/evaluator/edit/(?P<pk>[0-9]+)/$', views.editEvaluator, name='edit'),
    # url(r'^dashboard/evaluator/add/type/$', views.newTypeEvaluator, name='newtype'),
    url(r'^dashboard/evaluator/edit/type/(?P<pk>[0-9]+)/$', views.editTypeEvaluator, name='editType'),
    url(r'^dashboard/evaluator/list/institutional/$', views.searchInstitutional, name='searchInstitutional'),
    url(r'^dashboard/evaluator/list/degree/$', views.searchDegree, name='searchDegree'),
    url(r'^dashboard/evaluator/list/arcusur/$', views.searchArcusur, name='searchArcusur'),
    # url(r'^dashboard/evaluator/add/declaration/$', views.newDeclaration, name='newDeclaration'),
    url(r'^dashboard/evaluator/add/declaration/(?P<user>[0-9]+)$', views.newDeclaration, name='newDeclaration'),
    url(r'^dashboard/evaluator/edit/declaration/(?P<pk>[0-9]+)/$', views.editDeclaration, name='editDeclaration'),
    url(r'^dashboard/evaluator/list/declaration/$', views.viewDeclaration, name='viewDeclaration'),
    url(r'^dashboard/evaluator/declaration/$', views.searchDeclaration, name='searchDeclaration'),
    url(r'^dashboard/evaluator/cleanner/(?P<link>\w+)/$', views.cleanner, name='cleanner'),
    url(r'^dashboard/evaluator/list/view/$', views.EvaluatorList.as_view(), name='list'),
    url(r'^dashboard/evaluator/add/type/(?P<label>[0-9]+)/(?P<user>[0-9]+)$', views.newEvaluatorInstitutional, name='addType'),
    # url(r'^dashboard/evaluator/list/institutional/$', views.ListInstitutional.as_view(), name='listInstitutional'),
    url(r'^acreditation/api/v2/$', views.apiJson2, name='apiJson2'),
    url(r'^acreditation/api/v3/$', views.getTemplate, name='getTemplate'),
    url(r'^acreditation/api/v4/$', views.apiJson3, name='apiJson4'),
    # url(r'^acreditation/api/form/$', views.getTemplate, name='getTemplate'),
    url(r'^acreditation/api/v5/$', views.apiJson5, name='apiJson5'),
    url(r'^dashboard/evaluator/list/agronomia/$', views.ListAgronomia.as_view(), name='listAgronomia'),
    url(r'^dashboard/evaluator/(?P<pk>[0-9]+)/$', views.EvaluatorDetail.as_view(), name='EvaluatorDetail'),
    url(r'^acreditation/pdfevaluator/$', views.pdfEvaluator, name='pdfEvaluator'),
]

resolutions/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^dashboard/evaluator/resolution/view/$', views.viewResolution, name='view'),
    url(r'^dashboard/evaluator/resolution/new/$', views.ResolutionCreate.as_view(), name='new'),
    url(r'^dashboard/evaluator/resolution/list/$', views.ResolutionList.as_view(), name='list'),
    url(r'^dashboard/evaluator/resolution/edit/(?P<pk>\d+)$', views.ResolutionEdit.as_view(), name='edit'),
]

userprofiles/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^login/$', views.authentication, name='authentication'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/login'}, name="logout"),
]

templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <!--<meta name="viewport" content="width=divice-width, initial-scale=1, maximum-scale=1">-->
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title> {% block title %}  {% endblock %} </title>
</head>
<body>
    <section class="container">
        <header>
            <div class="page-header">
                <h4> {% block header %}  {% endblock %} </h4>
            </div>
        </header>
        {% block content %} {% endblock %}
    </section>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    {% block javascript %}  {% endblock %}
</body>
</html>

templates/layout.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=divice-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title> {% block title %}  {% endblock %} </title>
</head>
<body>
    <section class="container">
        <header>
            <div class="page-header">
                <h4> {% block header %}  {% endblock %} </h4>
            </div>
            {% if user.is_authenticated %}
                {% for item in user.user_profile.all %}
                    {% if item.number == 777 %}
                        {% include "menu_admin.html" %}
                    {% else %}
                        {% include "menu_operator.html" %}
                    {% endif %}
                {% endfor %}
            {% endif %}
        </header>

        {% block content %} {% endblock %}
    </section>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/acreditation.js' %}"></script>
    
</body>
</html>

templates/menu_admin.html
            <nav class="navbar navbar-inverse" role="navigation">
              <!-- El logotipo y el icono que despliega el menú se agrupan
                   para mostrarlos mejor en los dispositivos móviles -->
              <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse"
                        data-target=".navbar-ex1-collapse">
                  <span class="sr-only">Desplegar navegación</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'userprofiles:dashboard' %}">Inicio</a>
              </div>
             
              <!-- Agrupar los enlaces de navegación, los formularios y cualquier
                   otro elemento que se pueda ocultar al minimizar la barra -->
              <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Pares Evaluadores <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><a href="{% url 'evaluators:degree' %}">Grado</a></li>
                      <li><a href="{% url 'evaluators:institutional' %}">Institucional</a></li>
                      <li><a href="{% url 'evaluators:arcusur' %}">Arcusur</a></li>
                      <li><a href="{% url 'evaluators:evaluator' %}">Todos</a></li>
                      <li class="divider"></li>
                      <li><a href="{% url 'evaluators:new' %}">Agregar</a></li>
                    </ul>
                  </li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Carreras <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><a href="{% url 'namecareers:list' %}">Listar</a></li>
                      <li><a href="{% url 'namecareers:new' %}">Agregar</a></li>
                    </ul>
                  </li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Resoluciones <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><a href="{% url 'resolutions:view' %}">Listar</a></li>
                      <li><a href="{% url 'resolutions:new' %}">Agregar</a></li>
                    </ul>
                  </li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Nacionalidades <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><a href="{% url 'nationalities:view' %}">Listar</a></li>
                      <li><a href="{% url 'nationalities:new' %}">Agregar</a></li>
                    </ul>
                  </li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Declaraciones <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><a href="{% url 'evaluators:viewDeclaration' %}">Listar </a></li>
                    </ul>
                  </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Logout <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><a href="{% url 'userprofiles:logout' %}">{{ user.username }} </a></li>
                    </ul>
                  </li>
                </ul>
              </div>
            </nav>

templates/menu_operator.html
            <nav class="navbar navbar-inverse" role="navigation">
              <!-- El logotipo y el icono que despliega el menú se agrupan
                   para mostrarlos mejor en los dispositivos móviles -->
              <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse"
                        data-target=".navbar-ex1-collapse">
                  <span class="sr-only">Desplegar navegación</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'userprofiles:dashboard' %}">Inicio</a>
              </div>
             
              <!-- Agrupar los enlaces de navegación, los formularios y cualquier
                   otro elemento que se pueda ocultar al minimizar la barra -->
              <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Pares Evaluadores <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><a href="{% url 'evaluators:evaluator' %}">Todos</a></li>
                    </ul>
                  </li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Declaraciones <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><a href="{% url 'evaluators:viewDeclaration' %}">Listar </a></li>
                    </ul>
                  </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Logout <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><a href="{% url 'userprofiles:logout' %}">{{ user.username }} </a></li>
                    </ul>
                  </li>
                </ul>
              </div>
            </nav>