acreditation/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('careers.urls', namespace='careers')),
    url(r'^', include('evaluators.urls', namespace='evaluators')),
    url(r'^', include('userprofiles.urls', namespace='userprofiles')),
    url(r'^', include('namecareers.urls', namespace='namecareers')),
    url(r'^', include('resolutions.urls', namespace='resolutions')),
    url(r'^', include('nationalities.urls', namespace='nationalities')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

careers/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^acreditation/model/national/$', views.viewNational, name='national'),
    url(r'^acreditation/model/arcusur/$', views.viewArcusur, name='arcusur'),
    url(r'^acreditation/posgrado/$', views.viewPosgrado, name='postgrado'),
    url(r'^acreditation/postponed/$', views.viewPostponed, name='postponed'),
    url(r'^acreditation/no-reputable/$', views.viewNoReputable, name='noreputable'),
    url(r'^acreditation/history/$', views.viewHistory, name='history'),
    url(r'^acreditation/history/arcusur/$', views.viewHistoryArcusur, name='historyArcusur'),
    url(r'^acreditation/pdfnational/$', views.pdfNational, name='pdfNational'),
    url(r'^acreditation/pdfarcusur/$', views.pdfArcusur, name='pdfArcusur'),
    url(r'^acreditation/pdfpostponed/$', views.pdfPostponed, name='pdfPostponed'),
    url(r'^acreditation/pdfno-reputable/$', views.pdfNoReputable, name='pdfNoReputable'),
    url(r'^acreditation/pdfposgrado/$', views.pdfPosgrado, name='pdfPosgrado'),
    url(r'^acreditation/pdfhistory/$', views.pdfHistory, name='pdfHistory'),
    url(r'^acreditation/report/$', views.report, name='report'),
    url(r'^acreditation/cleanner/(?P<link>\w+)/$', views.cleanner, name='cleanner'),
    url(r'^acreditation/api/v1/$', views.careersJson, name='careersJson'),
    url(r'^acreditation/csvnational/$', views.exportCsvCareers, name='exportCsvCareers'),
    # url(r'^acreditation/v1/json/(?P<year>[0-9]+)/$', views.careersJson, name='careersJson'),
    # url(r'^acreditation/render-pdf/$', views.renderPdf, name='renderPdf'),
    # url(r'^acreditation/pdfnational/(?P<search>\w+[^/]+)/(?P<options>\w+)/$', views.pdfNational, name='pdfNational'),
    # url(r'^acreditation/pdfnational/(?P<search>\w+.+)/(?P<options>\w+)/$', views.pdfNational, name='pdfNational'),
    # url(r'^acreditation/pdfarcusur/(?P<search>\w+.+)/(?P<options>\w+)/$', views.pdfArcusur, name='pdfArcusur'),
]

resolutions/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^dashboard/evaluator/resolution/view/$', views.viewResolution, name='view'),
    url(r'^dashboard/evaluator/resolution/new/$', views.ResolutionCreate.as_view(), name='new'),
    url(r'^dashboard/evaluator/resolution/list/$', views.ResolutionList.as_view(), name='list'),
    url(r'^dashboard/evaluator/resolution/edit/(?P<pk>\d+)$', views.ResolutionEdit.as_view(), name='edit'),
]

resolutions/models.py
from __future__ import unicode_literals

from django.db import models
import datetime

# Create your models here.

class Resolution(models.Model):
    number = models.IntegerField(blank=False)
    start_date = models.DateField()
    end_date = models.DateField()
    document = models.FileField(upload_to='resolutions/%Y_%m_%d/')

    def __str__(self):
        return '(%d)-%s' %(self.number, self.start_date)

    class Meta:
        verbose_name = 'Resolution'
        verbose_name_plural = 'Resolutions'
        ordering = ('id',)

    def _get_term(self):
        return "%s / %s" %(self.start_date, self.end_date)

    def _get_date(self):
        return "%s" %(self.start_date)

    def _format_date(self):
        format = ('%Y')
        return self.start_date.strftime(format)
    
    years = property(_format_date)
    term = property(_get_term)

resolutions/forms.py
from django import forms

class FormSearchResolution(forms.Form):
    text = forms.CharField(label='Busqueda', error_messages={'required': 'Este campo es obligatorio'})

resolutions/views.py
# coding=utf-8

from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.template import loader
from django.http import HttpResponse
from .models import Resolution
from namecareers.forms import FormSearch
from django.core.paginator import Paginator, InvalidPage, EmptyPage



@login_required(login_url='/login/')
def viewResolution(request):
    title = 'Nombre de Carreras'
    template = loader.get_template('view_resolution.html')
    request.session['s_text'] = ''
    if request.method == 'POST':
        form = FormSearch(request.POST)
        if form.is_valid():
            search = request.POST['text']
            request.session['s_text'] = search
            listResolution = Resolution.objects.filter(number=search)
            context = {
                'title': title,
                'listResolution': listResolution,
                'form': form,
            }
            return HttpResponse(template.render(context, request))
    else:
        form = FormSearch()
    listPaginator = Resolution.objects.all()
    paginator = Paginator(listPaginator, 10)
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1
    try:
        listResolution = paginator.page(page)
    except (EmptyPage, InvalidPage):
        listResolution = paginator.page(paginator.num_pages)
    context = {
        'title': title,
        'listResolution': listResolution,
        'form': form,
    }
    return HttpResponse(template.render(context, request))


class ResolutionList(LoginRequiredMixin, ListView):
    login_url = '/login/'
    title = 'Resoluciones'
    model = Resolution
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(ResolutionList, self).get_context_data(**kwargs) 
        listResolution = Resolution.objects.all()
        paginator = Paginator(listResolution, self.paginate_by)
        try:
            page = int(self.request.GET.get('page', '1'))
        except ValueError:
            page = 1
        try:
            object_list = paginator.page(page)
        except (EmptyPage, InvalidPage):
            object_list = paginator.page(paginator.num_pages)
        context['object_list'] = object_list
        return context

class ResolutionCreate(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    title = 'Agregar nueva resolución'
    url = 'resolutions:view'
    success_url = reverse_lazy(url)
    model = Resolution
    fields = ['number', 'start_date', 'end_date', 'document', ]

class ResolutionEdit(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    title = 'Editar Resolución'
    url = 'resolutions:view'
    success_url = reverse_lazy(url)
    model = Resolution
    fields = ['number', 'start_date', 'end_date', 'document']

resolutions/templates/resolutions/resolution_form.html
{% extends 'layout.html' %}
{% load widget_tweaks %}

{% block title %}
    {{ view.title }}
{% endblock %}

{% block header %}  
    {{ view.title|upper }}
{% endblock %} 

{% block content %}

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
         <div class="form-group row">
                <label for="number" class="col-sm-2">Numero</label>
            <div class="col-sm-10">
                {% render_field form.number class="form-control" %}
                <strong class="text-danger"> {{ form.number.errors }} </strong>
            </div>
        </div>
        <div class="form-group row">
                <label for="start_date" class="col-sm-2">Fecha Inicio</label>
            <div class="col-sm-10">
                {% render_field form.start_date class="form-control" placeholder="dd/mm/aaaa" id="start" %}
                <strong class="text-danger"> {{ form.start_date.errors }} </strong>
            </div>
        </div>
        <div class="form-group row">
                <label for="end_date" class="col-sm-2">Fecha Fin</label>
            <div class="col-sm-10">
                {% render_field form.end_date class="form-control" placeholder="dd/mm/aaaa" id="end" %}
                <strong class="text-danger"> {{ form.end_date.errors }} </strong>
            </div>
        </div>
        <div class="form-group row">
                <label for="document" class="col-sm-2">Documento</label>
            <div class="col-sm-10">
                {% render_field form.document class="file" %}
                <strong class="text-danger"> {{ form.document.errors }} </strong>
            </div>
        </div>
        <button type="submit" class="btn btn-success pull-right">Guardar</button>
   </form>

{% endblock %}

resolutions/templates/resolutions/resolution_list.html
{% extends 'layout.html' %}
{% load widget_tweaks %}

{% block title %}
    {{ view.title }}
{% endblock %}

{% block header %}  
    {{ view.title|upper }}
{% endblock %} 

{% block content %}

    <table class="table table-condensed table-striped">
        <thead>
            <tr>
                <th colspan="4"><a href="{% url 'resolutions:new' %}" class="btn btn-success btn-sm"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a> </th>
            </tr>
            <tr>
                <th>Edit</th>
                <th>Numero</th>
                <th>Fecha</th>
                <th>Resolución</th>
            </tr>
        </thead>
        <tbody>
            {% for r in object_list %}
            <tr>
                <td> <a href="{% url 'resolutions:edit' r.id %}" class="btn btn-success btn-sm"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></a></td>
                <td> {{ r.number }} </td>
                <td> {{ r.start_date }} </td>
                <td> <a href="{{ r.document.url }}" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"> {{ r.number }}</a></td>
            </tr>
            {% endfor%}
        </tbody>
    </table>
    <ul class="pagination pagination-sm"> 
        {% if object_list.has_previous %}
            <li><a href="?page={{ object_list.previous_page_number }}" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></a></li>
        {% endif %}
        {% for pg in object_list.paginator.page_range %}
            {% if object_list.number == pg %}
                <li class="active"><a href="?page={{ pg }}">{{ pg }}</a></li>
            {% else %}
                <li><a href="?page={{ pg }}">{{pg}}</a></li>
            {% endif %}
        {% endfor %}
        {% if object_list.has_next %}
            <li><a href="?page={{ object_list.next_page_number }}" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></a></li>
        {% endif %}
    </ul>
{% endblock %}